theme: jekyll-theme-cayman
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: ML Model "#"1
    url: /model1/
  - title: ML Model "#"2
    url: /model2/
  - title: Team Members
    url: /teammembers/
  - title: Dataset Selection and Insights
    url: /datasetinfo/
  - title: Code for Visualization
    url: visualizationcode